typography_spectrum: 0.28266030612027193
content_rating:
  adult: false
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.08214680293128895
  lightness: 0.5116485499948619
  saturation: 0.8570453946253836
  rhythmicContrast: 0.6527717430526706
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.5008024691790657
author:
  name: Jukka Niiranen
  url: ''
  email: ''
name: Dynamics Survivor
navigation:
  - name: Surviving CRM blog
    url: 'http://survivingcrm.com/'
    type: external
title: Dynamics Survivor
description: Microsoft Dynamics 365 news and observations
