name: Dynamics Survivor
layout_spectrum: 0.683520058169961
typography_spectrum: 0.5491407623048872
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.9084346087183803
  lightness: 0.18014705856330693
  saturation: 0.26903930422849953
  rhythmicContrast: 0.6191812476608902
title: Microsoft Dynamics 365 news and observations
author:
  name: Jukka Niiranen
  url: ''
  email: ''
content_rating:
  adult: false
