typography_spectrum: 0.21109510073438287
content_rating:
  adult: false
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.9632477075792849
  lightness: 0.3037108692806214
  saturation: 0.8981009626295418
  rhythmicContrast: 0.5840101805515587
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.0325698833912611
author:
  name: Jukka Niiranen
  url: ''
  email: ''
name: Dynamics Survivor
title: Dynamics Survivor
description: Microsoft Dynamics 365 news and observations
